### ISSUE TITLE
i want list of all users participated in a hash

### ISSUE THREAD

**Issue by isoftmaster** [codingdefined/codingDefinedTrendingTweets#2]
If i want to see how many users participate in a trend or hash
or top 100 users list
how to do that in node.js and json

**Comment by codingdefined** [comment]
If the dates are more than a week old, you have to pay caz the free Twitter API won't do it. 
And if the dates are not more than a week than you have to use API GET https://api.twitter.com/1.1/search/tweets.json?q=#hashtag and count the number of distinct users.

**Comment by isoftmaster** [comment]
@codingdefined its not possible to count manually because i am asking about Trending topic which has minimum 20k tweets in 5hours 
how to count number of users participated in that hash?

**Comment by codingdefined** [comment]
@isoftmaster You are gonna need a paid service for that. You will not able to get this information from Free API
